/**SOH***********************************************************************************
Study #:                        Utility
Program Name:                   createhtml.sas
Purpose:                        To create program for
Original Author:                Chelsea Chen
Date Initiated:                 30-Jun-2020
Responsibility Taken Over by:   
Date Last Modified:             
Reason for Modification:  
Input data:                                                     
Output data:            
External macro referenced:      
SAS Version:                    V9.4
Program Version #:              1.0
**EOH***********************************************************************************/

%let dir=/data/dev/client60/ct-amt-061-02/dmc3;
%let shared=%str(S:\Client Folders\Client 60\CT-AMT-061-02\04_Biostatistics\08_QC and QA\00_QC and QA Plan\01_Records of Execution\08_DMC3 & NABfinal);
%let target=qcqa.html;
%let title1=CT-AMT-061-02 DMC3 QC/QA documentation;

%macro getdir(subdir=, prefix=, outdsn=);
 
  %local dsnames;
  %let   dsnames = dirlist owner;
  
  %do i=1 %to %sysfunc(countw(&dsnames));
    %local %scan(&dsnames,&i);
    data;stop;run;  %let %scan(&dsnames,&i)=%scan(&syslast,-1,.);
  %end;
     
  filename dirlist pipe "ls -lt &dir/&subdir";

  data &dirlist;
    length rwx $10 filename $ 50 owner $ 20;
    infile dirlist length=reclen missover firstobs=2;
    input rwx     $ 
          _link 
          owner   $ 
          group   $ 
          size
          month   $ 
          day     2.
          tmoryr  $ 
          filename $;     
    if find(rwx, "&prefix")=1;
  run;  
  
  proc freq data=&dirlist noprint;
    tables owner / out=&owner;
  run;

  data &outdsn;
    length subdir $ 20;
    set &owner;
    
    subdir="&outdsn";  
    keep subdir owner;
  run;
  
  proc datasets nolist;
    delete %do i=1 %to %sysfunc(countw(&dsnames));  %let j = %scan(&dsnames,&i);  &&&j %end;;
  quit;  
 
%mend getdir;

%getdir(subdir=output,            prefix=-, outdsn=output);
%getdir(subdir=programs/buildana, prefix=-, outdsn=buildana);
%getdir(subdir=programs/buildtab, prefix=-, outdsn=buildtab);
%getdir(subdir=qc,                prefix=d, outdsn=qc);

data third;
  length owner $ 20;
  owner='jmiller'; output;
  owner='sgulyas'; output;
run;

data all;
  length subfolder $ 50 path $ 1000 link $ 2000;
  
  set buildtab
      buildana
      output
      qc (in=inqc)
      third (in=in3rd);
       
  if inqc then subfolder='04_Validation';
  else if in3rd then subfolder='05_Third Level Review';
  else subfolder='03_Self Validation';
  
  path=catx('\', "&shared", subfolder, owner);
  link=cats("<a href=", quote(path), ">", owner, "</a>");
  
  label subfolder = "Sub-Directory"
        link = "Path to QC/QA documentation";
run;

proc freq data=all;
  tables subfolder*owner/list missing;
run;

proc sort data=all nodupkey;
  by subfolder owner;
run;

ods listing close;
ods html file="&dir/other/&target" STYLE=barrettsblue;

title "&title1";
proc print data=all noobs label;
  var link;
  id  subfolder;
run;
quit;
ods html close;
endsas;
data _null_;
  set all end=eof;

  file htm noprint notitle ls=175 ps=57 ll=ll n=ps;

  if _n_=1 then
  put "#--------------------------------------------------#"/
      "#   Script generated by backup.sas on %sysfunc(today(), yymmdd10.)   #"/
      "#--------------------------------------------------#"/;

  put "cd " dir /
      zip /
      attrib/;
      
  if eof then do;
    put "echo ---         THE END           ---"/
        "echo --- Good Night, and Good Luck ---"/
        "exit";
      end;
run;
